//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteThuongMaiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessory
    {
        public int PosterID { get; set; }
        public int CategoryID { get; set; }
        public string Device { get; set; }
        public string Material { get; set; }
        public string Guarantee { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Poster Poster { get; set; }
    }
}
