//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteThuongMaiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountGift
    {
        public int DiscountGiftID { get; set; }
        public int DiscountID { get; set; }
        public int PosterID { get; set; }
        public string ImageGift { get; set; }
        public string Description { get; set; }
    
        public virtual Discount Discount { get; set; }
        public virtual Poster Poster { get; set; }
    }
}
