//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteThuongMaiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaptopConfig
    {
        public int PosterID { get; set; }
        public int CategoryID { get; set; }
        public string Screen { get; set; }
        public string Camera { get; set; }
        public string RAM { get; set; }
        public string Disk { get; set; }
        public string CPU { get; set; }
        public string GPU { get; set; }
        public string Sound { get; set; }
        public string ODD { get; set; }
        public string USB { get; set; }
        public string LAN_Wifi { get; set; }
        public string OS { get; set; }
        public string Battery { get; set; }
        public string Size__H_x_W_x_D_ { get; set; }
        public string Weight { get; set; }
        public string Material { get; set; }
        public string Guarantee { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Poster Poster { get; set; }
    }
}
