//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteThuongMaiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDelivery
    {
        public int OrderDeliveryID { get; set; }
        public int OrderID { get; set; }
        public int DeliveryID { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual OrderA OrderA { get; set; }
    }
}
